config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  match "posts/index" => "posts#like", :via => :post, :as => :like

  match "follow/:id" => "users#follow", :via => :post, :as => :follow

  match "unfollow/:id" => "users#unfollow", :via => :delete, :as => :unfollow

  resources :posts
  resources :comments

  devise_for :users

  get "users/:id/show" => "users#show", :as => :show_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :image,
                    styles: {medium: '600x600>', thumb: '100x100' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image,
                        content_type: ['image/jpeg', 'image/gif', 'image/png']

  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follows, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :follows, source: :followed
  has_many :followers, through: :follows, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true, length: {maximum: 50}

  def following?(other_user)
    follows.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    follows.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    follows.find_by(followed_id: other_user.id).destroy!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permited_parameters, if: :devise_controller?

  private

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:edit, keys: [:name])
        
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy] 

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to :back
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end

  def correct_user
    @comment = Comment.find(params[:id])
    redirect_to(root_path) unless (current_user == @comment.user) || (current_user == @comment.post.user)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  
  include LikesHelper

  def index
    @posts = Post.all.reverse
    @post = Post.new
    @like = Like.new
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def like
    @like = Like.new(like_params)
    if like_exists?(@like.user_id, @like.post_id)
      old_like = Like.where(user_id: @like.user_id, post_id: @like.post_id).take
      Like.destroy(old_like.id)
    else
      @like.save
    end
    redirect_to :back
  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
    @comment = Comment.new
  end

  private


  def like_params
    params.require(:like).permit(:user_id, :post_id)
  end

  def post_params
    params.require(:post).permit(:body, :user_id, :image)
  end

  def correct_user
    @post = Post.find(params[:id])
    redirect_to(root_path) unless current_user == @post.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @followers = Follow.where(followed_id: @user.id)
    @followed_users = Follow.where(follower_id: @user.id)
  end


  def follow
    other_user = User.find(params[:id])
    current_user.follow!(other_user)
    redirect_to :back
  end

  def unfollow
    other_user = User.find(params[:id])
    current_user.unfollow!(other_user)
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper

  def like_exists?(user, post)
    Like.exists?(:user_id => user, :post_id => post)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :post_id, :value => p.id %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="text-right">
  <%= f.submit 'Comment', :class => "btn btn-success" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <h3>Edit comment</h3>
  <%= render 'form', p: @comment.post %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instadrom</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="navbar navbar-default">
    <div class="container">
      <%= link_to 'Instadrom', root_path, class: "navbar-brand" %>
      <div class="navbr-nav navbar-right">    
        <% if user_signed_in? %>
        <div class="pull-right">
          <p class="navbar-text">Hello, <%= link_to current_user.name, show_user_path(current_user) %></p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
        <% else %>
        <nav class="nav pull-right">
          <%= link_to 'Sign up', new_user_registration_path %>
          <%= link_to 'Log in', new_user_session_path %>
        </nav>
        <% end %>
      </div>
    </div>
  </header>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/likes/_form.html.erb
<%= form_for @like, url: like_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :post_id, :value => p.id %>
  <% if like_exists?(current_user.id, p.id ) %>
   <button class="btn btn-danger glyphicon glyphicon-thumbs-down"></button>
  <% else %>
   <button class="btn btn-success glyphicon glyphicon-thumbs-up"></button>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "What are you thinking about?", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form_control">
    <%= f.submit "Post it", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_like_form.html.erb
<%= form_for @like, url: like_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :post_id, :value => p.id %>
  <% if like_exists?(current_user.id, p.id ) %>
   <button class="glyphicon glyphicon-thumbs-down"></button>
  <% else %>
   <button class="glyphicon glyphicon-thumbs-up"></button>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h2>Edit post</h2>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">

  <div class="container-narrow">
    <div class="mb-20">
      <%= render 'form' %>
    </div>
    <div>

      <% @posts.each do |post| %>

      <div class="post mb-20">

        <h3 class="clearfix"><%= link_to post.user.name, show_user_path(post.user) %>
          <% if current_user == post.user %>
            <div class="btn-group pull-right ">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Post <span class="glyphicon glyphicon-option-vertical"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit', edit_post_path(post) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Аre you sure? The deleted post cannot be restored later" } %></li>
              </ul>
            </div>
          <% else %>
            <div class="pull-right">
              <% if current_user.following?(post.user) %>
                <%= link_to "Unfollow", unfollow_path(post.user), method: :delete, class: "btn btn-danger"  %>
              <% else %>
                <%= link_to "Follow", follow_path(post.user), method: :post, class: "btn btn-success" %>
              <% end %>
            </div>
          <% end %>
        </h3>

        <%= link_to image_tag(post.image.url(:medium)), post_path(post) %>
        <div class="clearfix mb-20">
          <div class="pull-left"><%= render 'likes/form', p: post %></div>
          <p class="pull-right">
          <% if post.likes.count != 0 %>
          <%= post.likes.count %> like<% if post.likes.count > 1 %>s <% end %>
          <% else %> No likes yet<% end %>
          </p>
        </div>
        
        <p><%= post.body %></p>
        <hr>
        <% if post.comments.size > 0 %>
        <% post.comments.each do |comment| %>
        <div class="comment">
          <h4>
            <%= comment.user.name %>
            <% if current_user == comment.user %>
            <div class="btn-group pull-right ">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-option-vertical"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit', edit_comment_path(comment) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Аre you sure? The deleted comment cannot be restored later" } %></li>
              </ul>
            </div>
            <% elsif current_user == post.user %>
            <%= link_to 'X', comment_path(comment), class: 'pull-right', method: :delete, data: { confirm: "Аre you sure? The deleted comment cannot be restored later" } %>
            <% end %>
          </h4>
          <p><%= comment.body %></p>
        </div>
        <% end %>
        <hr>
        <% else %>
        <p>Be the first one to comment it!</p>
        <% end %> 

        <div>
          <%= render 'comments/form', p: post %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/posts/new.html.erb
<div class="container">
  <h2>Add new post</h2>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post mb-20">
    <% post = @post %>
    <h3 class="clearfix"><%= link_to post.user.name, show_user_path(post.user) %>
      <% if current_user == post.user %>
      <div class="btn-group pull-right ">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Post <span class="glyphicon glyphicon-option-vertical"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to 'Edit', edit_post_path(post) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Аre you sure? The deleted post cannot be restored later" } %></li>
        </ul>
      </div>
      <% else %>
      <div class="pull-right">
        <% if current_user.following?(post.user) %>
        <%= link_to "Unfollow", unfollow_path(post.user), method: :delete, class: "btn btn-danger"  %>
        <% else %>
        <%= link_to "Follow", follow_path(post.user), method: :post, class: "btn btn-success" %>
        <% end %>
      </div>
      <% end %>
    </h3>

    <%= link_to image_tag(post.image.url(:medium)), post_path(post) %>
    <div class="clearfix mb-20">
      <div class="pull-left"><%= render 'likes/form', p: post %></div>
      <p class="pull-right">
        <% if post.likes.count != 0 %>
        <%= post.likes.count %> like<% if post.likes.count > 1 %>s <% end %>
        <% else %> No likes yet<% end %>
      </p>
    </div>

    <p><%= post.body %></p>
    <hr>
    <% if post.comments.size > 0 %>
    <% post.comments.each do |comment| %>
    <div class="comment">
      <h4>
        <%= comment.user.name %>
        <% if current_user == comment.user %>
        <div class="btn-group pull-right ">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-option-vertical"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit', edit_comment_path(comment) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Аre you sure? The deleted comment cannot be restored later" } %></li>
          </ul>
        </div>
        <% elsif current_user == post.user %>
        <%= link_to 'X', comment_path(comment), class: 'pull-right', method: :delete, data: { confirm: "Аre you sure? The deleted comment cannot be restored later" } %>
        <% end %>
      </h4>
      <p><%= comment.body %></p>
    </div>
    <% end %>
    <hr>
    <% else %>
    <p>Be the first one to comment it!</p>
    <% end %> 

    <div>
      <%= render 'comments/form', p: post %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.name %></h1>
  <div>
    <% unless current_user == @user %>
    <% if current_user.following?(@user) %>
    <%= link_to "Unfollow", unfollow_path(@user), method: :delete  %>
    <% else %>
    <%= link_to "Follow", follow_path(@user), method: :post %>
    <% end %>
    <% end %>
  </div>
  <div>
    <span><%= @followers.count %> followers</span>
    <span><%= @followed_users.count %> follows</span>
  </div>
  <div class="row">
    <% @user.posts.each do |post| %>

        <div class="post col-lg-4">
          <%= link_to image_tag(post.image.url(:medium)), post_path(post) %>
          <hr>
          <% if post.likes.count != 0 %>
          <p><%= post.likes.count %> like<% if post.likes.count > 1 %>s <% end %></p>
          <% else %>
          <p>No likes yet</p>
          <% end %>
        </div>
        <% end %>
  </div>
</div>